# PYTHON 3.7.3 

# BSG INSTITUTE

## Profesor : Daniel Chávez Gallo
_______________________________________________________________________________________________________________________________
_______________________________________________________________________________________________________________________________

### Verificar la versión de las librerias

In [2]:
import sys

print('Python version:', sys.version)

import IPython
print('IPython:', IPython.__version__)

import numpy
print('numpy:', numpy.__version__)

import pandas
print('pandas:', pandas.__version__)

Python version: 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
IPython: 7.4.0
numpy: 1.16.2
pandas: 0.24.2


In [3]:
import sys
sys.version

'3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]'

In [4]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

# Numpy

In [4]:
import numpy as np
?np

In [5]:
#Para la creación de un Array en Python
#1.Necesitamos importar la librería:
import numpy as np
#2.Creamos el array en Python:
n_array = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11],[8, 9, 10, 11]])

In [17]:
n_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11]])

In [22]:
n_array.ndim

2

In [24]:
?np.ndim

In [25]:
np.ndim(1)

0

In [26]:
np.ndim([1,2,3,4])

1

In [20]:
n_array.shape

(4, 4)

In [12]:
n_array2 = np.array([[3,4,5],[2,4]])

In [28]:
n_array2

array([list([3, 4, 5]), list([2, 4])], dtype=object)

In [27]:
n_array2.shape

(2,)

In [8]:
n_array3 = np.array([[3,4,5],[2,4,7],[2,4,7]])

In [9]:
n_array3.shape

(3, 3)

In [31]:
n_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11]])

In [32]:
#size: nos da el número de elementos.
n_array.size

16

In [33]:
n_array3.size

6

In [35]:
#dtype: nos da el tipo de los datos en el array.
n_array.dtype.name

dtype('int32')

In [36]:
#Restas de arrays.
a = np.array([11, 12, 13, 14])
b = np.array([ 1, 2, 3, 4])
c = a - b
c

array([10, 10, 10, 10])

In [43]:
#Restas de arrays.
a = np.array([11, 12, 13,0])
b = np.array([ 1, 2, 3, 4])
c = a % b
c

array([0, 0, 1, 0], dtype=int32)

In [10]:
#Potencia de arrays.
b**2

array([ 1,  4,  9, 16], dtype=int32)

In [11]:
#Funciones sobre los arrays.
np.cos(b)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [45]:
#Multiplicación de matrices
A1 = np.array([[1, 1],[0, 1]]) 
A2 = np.array([[2, 0],[3, 4]])

In [46]:
A1

array([[1, 1],
       [0, 1]])

In [47]:
A2

array([[2, 0],
       [3, 4]])

In [48]:
A1*A2

array([[2, 0],
       [0, 4]])

In [49]:
np.dot(A1,A2)

array([[5, 4],
       [3, 4]])

In [50]:
# Selección elementos
#Si deseamos seleccionar un elemento en particular de un array:
#Seleccionamos la fila 1 y la columna 2.
n_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11]])

In [51]:
n_array[3,3]

11

In [53]:
#Seleccionamos la fila 1 y las 3 primeras columnas.
n_array[ 0 , 2:3 ]

array([2])

In [55]:
n_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11]])

In [59]:
#Seleccionamos la fila 1 y todas las columnas.
n_array[2,  ]

array([ 8,  9, 10, 11])

In [58]:
n_array[:,2]

array([ 2,  6, 10, 10])

In [60]:
#Seleccionamos todas las filas y la columna 2.
n_array[ : , 1 ]

array([1, 5, 9, 9])

In [61]:
#Modificamos la dimensionalidad de un array llevándolo de dimensión 1xN.
n_array.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  8,  9, 10, 11])

In [62]:
n_array.shape

(4, 4)

In [63]:
#Modificamos la dimensionalidad del array llevándola a 6 filas x 2 columnas.
n_array.shape = (8,2)

In [64]:
n_array

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [ 8,  9],
       [10, 11]])

In [65]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [71]:
range(8)

range(0, 8)

In [72]:
np.arange(5,9)

array([5, 6, 7, 8])

In [73]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [76]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [77]:
range(0,1,0.1)

TypeError: 'float' object cannot be interpreted as an integer

In [78]:
lis1 =[2,3,4]
lis2 = [4,2,6]

In [79]:
lis3 = (lis1, lis2)

In [80]:
lis3

([2, 3, 4], [4, 2, 6])

In [81]:
np.array(lis3)

array([[2, 3, 4],
       [4, 2, 6]])

In [82]:
ray = np.arange(2,20,3)

In [83]:
ray[0]

2

In [85]:
ray

array([ 2,  5,  8, 11, 14, 17])

In [86]:
ray[1:4]

array([ 5,  8, 11])

In [88]:
ray[-1]

17

In [90]:
ray[-2]

14

In [91]:
ray

array([ 2,  5,  8, 11, 14, 17])

In [93]:
ray2 = ray.copy()

In [94]:
ray2

array([ 2,  5,  8, 11, 14, 17])

In [95]:
array2 = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [96]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
array2[0]

array([1, 2, 3])

In [98]:
array2[1][0]

4

In [99]:
array2[1,0]

4

In [101]:
array2[,0]

SyntaxError: invalid syntax (<ipython-input-101-b04405be7dee>, line 1)

In [103]:
array2[:][0]

array([1, 2, 3])

In [105]:
ray[:]

array([ 2,  5,  8, 11, 14, 17])

In [106]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [107]:
np.arange(15).shape

(15,)

In [108]:
np.arange(15).reshape

<function ndarray.reshape>

In [120]:
array1 = np.arange(15).reshape((3,5), order = 'C')

In [121]:
array1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [114]:
?np.reshape

In [115]:
array2 = np.arange(15).reshape((3,5),order='F')

In [116]:
array2

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [117]:
array3 = np.arange(15).reshape((3,5),order='A')

In [118]:
array3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [123]:
array4 = array3.T

In [124]:
array4

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [125]:
print(array3.shape);
print(array4.shape);

(3, 5)
(5, 3)


In [130]:
result = np.zeros(9).reshape((3,3))

In [131]:
result

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [135]:
range(len(array4[0]))

range(0, 3)

In [132]:
for i in range(len(array3)):   
   for j in range(len(array4[0])):       
       for k in range(len(array4)):
            result[i][j] += array3[i][k] * array4[k][j]

for r in result:
   print(r)

[ 30.  80. 130.]
[ 80. 255. 430.]
[130. 430. 730.]


In [136]:
result

array([[ 30.,  80., 130.],
       [ 80., 255., 430.],
       [130., 430., 730.]])

In [138]:
np.sqrt(result)

array([[ 5.47722558,  8.94427191, 11.40175425],
       [ 8.94427191, 15.96871942, 20.73644135],
       [11.40175425, 20.73644135, 27.01851217]])

In [139]:
np.sqrt(result).round(2)

array([[ 5.48,  8.94, 11.4 ],
       [ 8.94, 15.97, 20.74],
       [11.4 , 20.74, 27.02]])

In [140]:
np.random.rand(8)

array([0.60864339, 0.08748167, 0.99621807, 0.01396958, 0.12615394,
       0.46593629, 0.4102645 , 0.09739962])

In [143]:
?np.random.rand

In [145]:
np.random.rand(8,3).round(2)

array([[0.37, 0.67, 0.97],
       [0.45, 0.98, 0.81],
       [0.48, 0.42, 0.8 ],
       [0.32, 0.22, 0.6 ],
       [0.62, 0.79, 0.84],
       [0.12, 0.03, 0.84],
       [0.31, 0.18, 0.62],
       [0.16, 0.45, 0.26]])

In [151]:
np.random.rand(2,3,4).round(2)

array([[[0.37, 0.32, 0.99, 0.74],
        [0.71, 0.04, 0.39, 0.35],
        [0.77, 0.79, 0.79, 0.64]],

       [[0.72, 0.84, 0.33, 0.23],
        [0.61, 0.95, 0.28, 0.27],
        [0.46, 0.82, 0.15, 0.92]]])

In [150]:
np.random.rand(2,3,4).round(2).shape

(2, 3, 4)

In [152]:
np.random.rand(2,3,4,2).round(2)

array([[[[0.7 , 0.25],
         [0.11, 0.44],
         [0.46, 0.35],
         [0.54, 0.75]],

        [[0.12, 0.7 ],
         [0.42, 0.45],
         [0.13, 0.97],
         [0.4 , 0.3 ]],

        [[0.89, 0.77],
         [0.75, 0.53],
         [0.02, 0.95],
         [0.62, 0.38]]],


       [[[0.22, 0.62],
         [0.89, 0.49],
         [0.3 , 0.54],
         [0.41, 0.13]],

        [[0.72, 0.  ],
         [0.57, 0.74],
         [0.55, 0.43],
         [0.87, 0.85]],

        [[0.6 , 0.1 ],
         [0.73, 0.82],
         [0.48, 0.62],
         [0.85, 0.26]]]])

In [159]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [160]:
np.random.rand(4)

array([0.78733787, 0.05202274, 0.8158832 , 0.68740703])

In [193]:
np.random.randint(1,20,10)

array([ 7,  7, 19, 18,  7,  3, 14,  6, 11,  2])

# Pandas

In [194]:
#Las series son un array de una dimensión, pueden almacenar cualquier tipo de datos como valores discretos, continuos, cadenas y objetos Python.

#Importar la librería Pandas desde Python.
import pandas as pd

In [196]:
np.random.randn(5)

array([ 2.02370040e+00, -2.39552646e+00,  2.19261586e-01,  6.15812525e-04,
       -3.97409877e-01])

In [197]:
#Creación de una serie a partir de 5 números aleatorios.
mat1 = pd.Series(np.random.randn(5))

In [202]:
mat1

0   -1.311838
1    0.522841
2    0.247271
3   -0.432671
4   -0.965366
dtype: float64

In [200]:
np.random.randn(5,2)

array([[ 0.01864503,  2.01060856],
       [-2.18383753, -0.79644109],
       [ 1.8740468 ,  0.55999449],
       [-1.39411777, -0.90909312],
       [ 2.64061137, -0.50631521]])

In [201]:
pd.Series(np.random.randn(5,2))

Exception: Data must be 1-dimensional

In [203]:
pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])

a   -0.291447
b   -0.041362
c    0.545821
d    0.824505
e   -0.069465
dtype: float64

In [204]:
#Data Frames que provienen de diccionarios de series.
d = {'c1': pd.Series(['A', 'B', 'C']),'c2': pd.Series([1, 2., 3., 4.])}
df = pd.DataFrame(d)
df

c1   c2
0    A  1.0
1    B  2.0
2    C  3.0
3  NaN  4.0

In [205]:
#Data Frames que provienen de diccionarios de listas.
d = {'c1': ['A', 'B', 'C', 'D'],'c2': [1, 2.0, 3.0, 4.0]}
df = pd.DataFrame(d)
df

c1   c2
0  A  1.0
1  B  2.0
2  C  3.0
3  D  4.0

In [207]:
pd.DataFrame(np.random.randn(4, 3))

0         1         2
0  0.492452 -1.360653  0.444556
1 -1.613182  0.719399  1.682387
2  0.627880  0.422021 -1.315398
3 -1.460406  0.148411 -0.408806

In [208]:
pd.DataFrame(np.random.randn(4, 2))

0         1
0 -0.609533 -0.344410
1  1.122597  0.383825
2  0.432625  0.952286
3  0.156335 -0.991601

In [209]:
#Es una estructura de datos de 3 dimensiones.
#Data Frames que provienen de diccionarios de series.
d = {'Item1': pd.DataFrame(np.random.randn(4, 3)),
'Item2': pd.DataFrame(np.random.randn(4, 2))}
pd.Panel(d)
d

C:\Users\Daniel\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3296: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


{'Item1':           0         1         2
 0 -0.900135 -0.093718  0.154208
 1  0.501024  0.200331  1.234568
 2  0.481512 -1.543753 -1.723864
 3  0.947528 -0.402745  0.135097, 'Item2':           0         1
 0 -0.733217 -0.536776
 1 -0.949513  0.142544
 2 -0.006512 -0.576034
 3 -1.736485  1.579227}

## Lectura de datos

In [210]:
?pd.read_csv

In [212]:
import sys
sys.path

['C:\\Users\\Daniel\\Documents\\BSG\\02 Python\\Python BSG',
 'C:\\Users\\Daniel\\Anaconda3\\python37.zip',
 'C:\\Users\\Daniel\\Anaconda3\\DLLs',
 'C:\\Users\\Daniel\\Anaconda3\\lib',
 'C:\\Users\\Daniel\\Anaconda3',
 '',
 'C:\\Users\\Daniel\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\Daniel\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Daniel\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Daniel\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Daniel\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Daniel\\.ipython']

In [218]:
#Importar datos en formato csv.
d = pd.read_csv('Datos/base_intro.csv', sep=',')

In [219]:
#Leer los primeros registros.
d.head(3)

nit  en_vm_canal1  en_vm_canal2  en_vm_canal3  \
0   C4936394968152386565           0.0          0.00          0.00   
1  C-8615176103348111575           0.0          0.00          0.00   
2   C2364605246729357060   250927492.7   54160892.46    5122151.67   

   en_vm_canal4  en_vm_canal5  en_vm_canal6  en_vm_canal7  en_vm_canal8  \
0          0.00           0.0           0.0  0.000000e+00           0.0   
1          0.00           0.0           0.0  0.000000e+00           0.0   
2   41852510.17   413614314.7     1663236.4  2.106848e+09           0.0   

   en_vm_canal9  ...  pagos_pn  tiene_ventas_fisicas  \
0           0.0  ...     0.000                   0.0   
1           0.0  ...     0.000                   0.0   
2           0.0  ...     0.544                   1.0   

  tiene_ventas_electronicas recaudos_pj recaudos_pn rotacion_inventarios  \
0                       0.0         0.0         0.0                  6.0   
1                       0.0         0.0         0.0                  1.0   
2                       0.0         0.0         0.0                  2.0   

  rotacion_cxc rotacion_cxp ciclo_negocio ciclo_financiero  
0          2.0          2.0           5.0              6.0  
1          3.0          1.0           3.0              4.0  
2          1.0          2.0           2.0              1.0  

[3 rows x 47 columns]

In [220]:
d.tail(3)

nit  en_vm_canal1  en_vm_canal2  en_vm_canal3  \
2230  C-183565186626737291           0.0           0.0           0.0   
2231  C-183565186626737291           0.0           0.0           0.0   
2232  C-183565186626737291           0.0           0.0           0.0   

      en_vm_canal4  en_vm_canal5  en_vm_canal6  en_vm_canal7  en_vm_canal8  \
2230           0.0           0.0           0.0           0.0           0.0   
2231           0.0           0.0           0.0           0.0           0.0   
2232           0.0           0.0           0.0           0.0           0.0   

      en_vm_canal9  ...  pagos_pn  tiene_ventas_fisicas  \
2230           0.0  ...       0.0                   0.0   
2231           0.0  ...       0.0                   0.0   
2232           0.0  ...       0.0                   0.0   

     tiene_ventas_electronicas recaudos_pj recaudos_pn rotacion_inventarios  \
2230                       0.0         0.0         0.0                  2.0   
2231                       0.0         0.0         0.0                  1.0   
2232                       0.0         0.0         0.0                  1.0   

     rotacion_cxc rotacion_cxp ciclo_negocio ciclo_financiero  
2230          2.0          1.0           3.0              4.0  
2231          2.0          1.0           2.0              3.0  
2232          1.0          4.0           2.0              1.0  

[3 rows x 47 columns]

In [221]:
d.shape

(2233, 47)

In [225]:
#Leer registros específicos de una variable
d[80:5000][['pagos_pn','ciclo_negocio']]

pagos_pn  ciclo_negocio
80       0.223            2.0
81       0.458            5.0
82       0.703            4.0
83       0.799            2.0
84       0.535            6.0
85       0.000            2.0
86       0.616            4.0
87       0.000            2.0
88       0.081            4.0
89       0.670            2.0
90       0.662            6.0
91       0.547            5.0
92       0.682            6.0
93       0.100            2.0
94       0.198            4.0
95       0.525            4.0
96       0.336            3.0
97       0.940            2.0
98       0.590            6.0
99       0.137            4.0
100      0.720            4.0
101      0.928            4.0
102      0.436            1.0
103      0.960            2.0
104      0.183            5.0
105      0.934            4.0
106      0.646            5.0
107      0.000            4.0
108      0.207            1.0
109      0.651            4.0
...        ...            ...
2203     0.171            5.0
2204     0.086            6.0
2205     0.000            6.0
2206     0.000            5.0
2207     0.000            5.0
2208     0.000            6.0
2209     0.000            5.0
2210     0.000            6.0
2211     0.000            1.0
2212     0.000            6.0
2213     0.000            5.0
2214     0.000            4.0
2215     0.000            5.0
2216     0.000            4.0
2217     0.000            3.0
2218     0.000            6.0
2219     0.000            6.0
2220     0.000            5.0
2221     0.000            4.0
2222     0.000            5.0
2223     0.000            1.0
2224     0.000            1.0
2225     0.000            3.0
2226     0.000            5.0
2227     0.000            6.0
2228     0.000            6.0
2229     0.000            5.0
2230     0.000            3.0
2231     0.000            2.0
2232     0.000            2.0

[2153 rows x 2 columns]

In [226]:
#Exportar datos de un data frame a un csv
d = {'c1': pd.Series(['A', 'B', 'C']),'c2': pd.Series([1, 2., 3., 4.])}
df = pd.DataFrame(d)
df.to_csv('Datos/sample_data2.csv')

In [227]:
#Importar datos en formato xls.
d = pd.read_excel('Datos/sample_data.xlsx')

In [228]:
d.head()

Unnamed: 0   c1  c2
0           0    A   1
1           1    B   2
2           2    C   3
3           3  NaN   4

In [28]:
df.to_excel('Datos/sample_data.xlsx')

In [234]:
dataframe_nba = pd.read_clipboard()

In [235]:
dataframe_nba.head()

en_vm_canal3  en_vm_canal4  en_vm_canal5  en_vm_canal6  en_vm_canal7  \
0  0.000000e+00          0.00           0.0          0.00             0   
1  0.000000e+00          0.00           0.0          0.00             0   
2  5.122152e+06   41852510.17   413614314.7    1663236.40    2106847525   
3  8.226710e+06          0.00           0.0    7072801.90             0   
4  1.053441e+08   15755286.83           0.0   23671840.33             0   

   en_vm_canal8  en_vm_canal9  en_vm_canal10  
0           0.0          0.00              0  
1           0.0          0.00              0  
2           0.0          0.00              0  
3     9000000.0          0.00              0  
4     3600962.2    3727298.56              0

In [236]:
dataframe_nba.columns

Index(['en_vm_canal3', 'en_vm_canal4', 'en_vm_canal5', 'en_vm_canal6',
       'en_vm_canal7', 'en_vm_canal8', 'en_vm_canal9', 'en_vm_canal10'],
      dtype='object')

In [237]:
dataframe_nba['en_vm_canal4']

0            0.00
1            0.00
2     41852510.17
3            0.00
4     15755286.83
5            0.00
6            0.00
7            0.00
8     58128720.92
9            0.00
10    43250552.50
11           0.00
12    71462637.33
13           0.00
14           0.00
Name: en_vm_canal4, dtype: float64

In [239]:
dataframe_nba.loc[5]

en_vm_canal3     1348792.0
en_vm_canal4           0.0
en_vm_canal5           0.0
en_vm_canal6     3828360.0
en_vm_canal7           0.0
en_vm_canal8           0.0
en_vm_canal9      687244.0
en_vm_canal10          0.0
Name: 5, dtype: float64

In [246]:
dataframe_nba.loc[2]

en_vm_canal3     5.122152e+06
en_vm_canal4     4.185251e+07
en_vm_canal5     4.136143e+08
en_vm_canal6     1.663236e+06
en_vm_canal7     2.106848e+09
en_vm_canal8     0.000000e+00
en_vm_canal9     0.000000e+00
en_vm_canal10    0.000000e+00
Name: 2, dtype: float64

In [244]:
dataframe_nba.describe().round(2)

en_vm_canal3  en_vm_canal4  en_vm_canal5  en_vm_canal6  en_vm_canal7  \
count  1.500000e+01         15.00  1.500000e+01  1.500000e+01  1.500000e+01   
mean   1.495458e+08   15363313.85  1.582385e+08  2.203037e+07  2.122776e+08   
std    5.164205e+08   25093905.78  2.903057e+08  3.895108e+07  5.930244e+08   
min    0.000000e+00          0.00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    1.875000e+05          0.00  0.000000e+00  0.000000e+00  0.000000e+00   
50%    1.348792e+06          0.00  0.000000e+00  1.663236e+06  0.000000e+00   
75%    1.398088e+07   28803898.50  1.971147e+08  2.446192e+07  0.000000e+00   
max    2.012687e+09   71462637.33  8.846509e+08  1.344848e+08  2.106848e+09   

       en_vm_canal8  en_vm_canal9  en_vm_canal10  
count         15.00         15.00          15.00  
mean     5015703.32    3966037.80      769220.00  
std      9670417.00    8848265.58     2979176.25  
min            0.00          0.00           0.00  
25%            0.00          0.00           0.00  
50%            0.00          0.00           0.00  
75%      4781511.16    4826011.78           0.00  
max     30779975.17   34572612.78    11538300.00

In [248]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [247]:
lista_valores = np.arange(9).reshape(3,3)
lista_indices = ['a','b','c']
lista_columnas = ['c1','c2','c3']

dataframe = pd.DataFrame(lista_valores, index=lista_indices, columns=lista_columnas)

dataframe


c1  c2  c3
a   0   1   2
b   3   4   5
c   6   7   8

In [249]:
dataframe.drop('b')

c1  c2  c3
a   0   1   2
c   6   7   8

In [253]:
dataframe.drop('c2', axis = 1)

c1  c3
a   0   2
b   3   5
c   6   8

In [262]:
?pandas.DataFrame.drop

In [263]:
dataframe

c1  c2  c3
a   0   1   2
b   3   4   5
c   6   7   8

In [264]:
dataframe['c3']

a    2
b    5
c    8
Name: c3, dtype: int32

In [267]:
dataframe

c1  c2  c3
a   0   1   2
b   3   4   5
c   6   7   8

In [271]:
dataframe['c2']['a']

1

In [272]:
dataframe['c2']['c']

7

In [275]:
dataframe[['c2','c3']]

c2  c3
a   1   2
b   4   5
c   7   8

In [276]:
dataframe[dataframe['c2'] > 1]

c1  c2  c3
b   3   4   5
c   6   7   8

In [277]:
dataframe[dataframe['c1'] < 6]

c1  c2  c3
a   0   1   2
b   3   4   5

In [297]:
np.random.randn(10)

array([ 0.27926258, -2.2277193 ,  0.83904624,  0.46128003, -1.84695727,
       -0.75370334, -0.43000141,  0.11648405, -1.32944147,  0.94066694])

In [298]:
serie2 = pd.Series(np.random.randn(10))

In [280]:
serie2.sort_values()

6   -1.307168
2   -0.905660
1   -0.534323
0   -0.312220
9    0.023363
4    0.234127
5    1.025580
7    1.046767
8    1.420632
3    1.610756
dtype: float64

In [299]:
serie2.sort_index()

0   -0.232266
1   -1.212702
2    0.579806
3    0.705830
4   -0.603409
5    1.398567
6    1.028207
7   -0.037672
8    0.120914
9    1.046453
dtype: float64

In [301]:
?pd.DataFrame.sort_values

In [302]:
dataframe

c1  c2  c3
a   0   1   2
b   3   4   5
c   6   7   8

In [304]:
dataframe.sort_values(by=['c3'], ascending = False)

c1  c2  c3
c   6   7   8
b   3   4   5
a   0   1   2

In [ ]:
#-------------------- por filas

In [317]:
dataframe.sum()

c1     9
c2    12
c3    15
dtype: int64

In [319]:
dataframe.sum(axis = 1)

a     3
b    12
c    21
dtype: int64

In [320]:
dataframe.min()

c1    0
c2    1
c3    2
dtype: int32

In [321]:
dataframe.min(axis = 1)

a    0
b    3
c    6
dtype: int32

In [322]:
dataframe.mean()

c1    3.0
c2    4.0
c3    5.0
dtype: float64

In [326]:
np.sqrt(dataframe.var(axis = 1))

a    1.0
b    1.0
c    1.0
dtype: float64

In [328]:
?pd.isnull

In [329]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])

In [330]:
array

array([[ 1., nan,  3.],
       [ 4.,  5., nan]])

In [332]:
pd.isnull(array)

array([[False,  True, False],
       [False, False,  True]])