In [12]:
a = 5
b = 6
a * b

30

In [13]:
# VARIABLES

numero = 5
numero

5

In [25]:
cadena = "mi nombre es, Didier"

In [26]:
cadena

'mi nombre es, Didier'

In [27]:
cadena2 = "mi nombre es, Hugo"

In [28]:
cadena2

'mi nombre es, Hugo'

In [24]:
print(cadena)
print(cadena2)

mi nombre es, Didier
mi nombre es, Hugo


In [26]:
type(numero)

int

In [28]:
type(cadena)

str

In [32]:
Tallas = [1.74, 1.80]
type(Tallas)

list

In [34]:
peso = 92.40

In [37]:
type(peso)

float

In [40]:
cadena = "3"
int(cadena)

3

In [42]:
len(cadena)

1

In [44]:
cadena2[4]

'o'

In [46]:
cadena2[-2]

'g'

In [50]:
cadena3 = "MI NOMBRE ES DIDIER YEPEZ"
cadena3.lower()

'mi nombre es didier yepez'

In [52]:
cadena3.upper()

'MI NOMBRE ES DIDIER YEPEZ'

In [54]:
cadena2.split(",")

['mi nombre es', ' Hugo']

In [56]:
cadena.split("e")

['3']

In [62]:
cadena2.split("e")

['mi nombr', ' ', 's, Hugo']

In [64]:
len(cadena2.split("e"))

3

In [68]:
alumno = "Didier"
print("mi nombre es " + alumno)

mi nombre es Didier


In [82]:
edad = 27
print("Buenos dias, mi nombre es " + alumno + " y mi edad es " + str(edad))

Buenos dias, mi nombre es Didier y mi edad es 27


In [79]:
print("Buenos dias {}, feliz {} cumpleaños".format(alumno,edad))

Buenos dias Didier, feliz 27 cumpleaños


In [81]:
print(f"Buenos dias {alumno}, feliz {edad} cumpleaños")

Buenos dias Didier, feliz 27 cumpleaños


In [84]:
R = 10/3;R

3.3333333333333335

In [86]:
print(f"el resultado es {R}")

el resultado es 3.3333333333333335


In [ ]:
print("Introduzca un nombre")
entrada2 = input()
print("se ingreso ingresado es " + entrada2)

In [2]:
8+9

17

In [4]:
2^2

0

In [6]:
2*2

4

In [10]:
a = 3; b = 4; c = 6
print(a-b)
print(b/a)

-1
1.3333333333333333


In [12]:
-b

-4

In [13]:
a==b

False

In [16]:
a!=b

True

In [18]:
a>b

False

In [20]:
a<b

True

In [29]:
cadena == cadena2

False

In [31]:
persona = input("Ingrese nombre de la persona: ")
sexo = input("ingrese sexo; ")
if nombre[0] <= "M" and sexo == "HOMBRE":
    print("grupo a")
    elif nombre [0] >= "N" and sexo == "MUJER":
        print("grupo b")
        else:
            print("grupo c")

SyntaxError: invalid syntax (<ipython-input-31-6e19af2abb9b>, line 5)

In [34]:
n1 = 5; n2 = 6; n3 = 12; n4 = 20

In [36]:
(n1<n2) and (n1>n4)

False

In [38]:
(n1<n2) and (n1<n4)

True

In [ ]:
##EL ^  hace de ||

In [39]:
(n1<n2) ^ (n1>n4)

True

In [41]:
frutas = ["Pera","Mango","Manzana","Uvas","Melón"]; Fruta = "Maracuya"

In [43]:
Fruta in frutas 

False

In [45]:
Fruta1 = "Mango"

In [47]:
Fruta1 not in frutas

False

In [49]:
Fruta2 = "Manzana"

In [51]:
Fruta2 in frutas

True

In [56]:
##lista de listas
autos = [["Yaris","Fortuner"],["Accent","Santa Fe"],[4,5],40]
len(autos)

4

In [58]:
autos[3]

40

In [68]:
tupla_colores = ("Verde","Amarillo","Rojo")

In [62]:
tupla_colores[2]

'Rojo'

In [71]:
for color in tupla_colores:
     print(color)

Verde
Amarillo
Rojo


In [74]:
auto = (["Yaris","Fortuner"],["Accent","Santa Fe"],[4,5],40)
auto[0]


['Yaris', 'Fortuner']

In [77]:
auto[0][0] = "X5"

In [79]:
auto[0][0]

'X5'

In [81]:
auto[0]

['X5', 'Fortuner']

In [87]:
conj_color = {"Celeste","Marron","Negro",4,("Daniel","Hugo")}

for color in conj_color:
    print(color)

4
Celeste
('Daniel', 'Hugo')
Negro
Marron


In [90]:
diccionario = {"red":"rojo","Blue":"Azul","Green":"Verde"}
diccionario

{'red': 'rojo', 'Blue': 'Azul', 'Green': 'Verde'}

In [92]:
for color in diccionario:
    print(color)

red
Blue
Green


In [94]:
diccionario["red"]

'rojo'

In [97]:
if(n1>n2):
    print("n1 es mayor a n2")
elif(n1==n2):
    print("n1 es igual a n2")
else:
    print("ninguna de las anteriores")

ninguna de las anteriores


In [103]:
def compnum(n1,n2):
    if(n1>n2):
        print("n1 es mayor a n2")
    elif(n1==n2):
        print("n1 es igual a n2")
    else:
        print("ninguna de las anteriores")


In [105]:
compnum(54,60)

ninguna de las anteriores


In [108]:
i = 1
while(i<=10):
    print(i)
    i+=1

1
2
3
4
5
6
7
8
9
10


In [128]:
i = 1
while(i>=-10):
    print(i)
    i-=1

1
0
-1
-2
-3
-4
-5
-6
-7
-8
-9
-10


In [131]:
class ClaseSilla:
    color="Negro"
    precio=250
    patas = 4
    tamano = 0.60
    
    

In [133]:
ClaseSilla

__main__.ClaseSilla

In [135]:
type(ClaseSilla)

type

In [137]:
obj_silla = ClaseSilla()

In [139]:
obj_silla.tamano

0.6

In [141]:
obj_silla.tamano ** 2

0.36

In [143]:
lista1 = [["Amarillas","Blancas",obj_silla.color], 40, "Daniel"]

In [145]:
lista1

[['Amarillas', 'Blancas', 'Negro'], 40, 'Daniel']

In [149]:
R2 = lambda W : W + 30 ## ES UNA FUNCION QUE PUEDES PASARLE N PARAMETROS Y HACER OPERACIONES CON ELLOS

In [151]:
R2

<function __main__.<lambda>(W)>

In [153]:
R2(8)

38

In [156]:
def compnum(n1,n2):
    if(n1>n2):
        print("n1 es mayor a n2")
    elif(n1==n2):
        print("n1 es igual a n2")
    else:
        print("ninguna de las anteriores")

In [166]:
def division(a,b):
	if(b==0):
		print("Error division por 0")
	else:
		print(a/b)

In [169]:
import plotly

In [173]:
import re
help(re)

Help on module re:

NAME
    re - Support for regular expressions (RE).

DESCRIPTION
    This module provides regular expression matching operations similar to
    those found in Perl.  It supports both 8-bit and Unicode strings; both
    the pattern and the strings being processed can contain null bytes and
    characters outside the US ASCII range.
    
    Regular expressions can contain both special and ordinary characters.
    Most ordinary characters, like "A", "a", or "0", are the simplest
    regular expressions; they simply match themselves.  You can
    concatenate ordinary characters, so last matches the string 'last'.
    
    The special characters are:
        "."      Matches any character except a newline.
        "^"      Matches the start of the string.
        "$"      Matches the end of the string or just before the newline at
                 the end of the string.
        "*"      Matches 0 or more (greedy) repetitions of the preceding RE.
                 Greedy 

In [174]:
#si quiero traer toda la libreria
import datetime

In [177]:
#si quiero traer una funcion de una libreria
from datetime import datetime

datetime.now()

datetime.datetime(2020, 2, 1, 11, 22, 45, 269780)

In [182]:
numeros = [-4,-3,5,7]

In [192]:
def positivo(num):
    if(num>0):
        return True
    else:
        return False
    

In [193]:
R = list(filter(positivo, numeros))

In [194]:
R

[5, 7]

In [215]:
def pares(num):
    if(num/2%0):
        return True
    else:
        return False

In [217]:
P = list(filter(pares,numeros))

ZeroDivisionError: float modulo

In [266]:
numeros2 = list(map(lambda num: num ** 2, numeros))


In [267]:
numeros2

[16, 9, 25, 49]

In [257]:
import math as mt
mt.sqrt(9)

3.0

In [260]:
def raiz(num):
    return(mt.sqrt(num))

In [268]:
list(map(raiz, numeros2))


[4.0, 3.0, 5.0, 7.0]

In [284]:
## EJERCICIO CONVERTIR TEMPERATURAS DE FARENHEITH A CELSIUS
def EvaluarTemperatura(num):
    centigrados = (num - 32) * (5/9)
    if(centigrados < 35):
        print("Escalofrios")
    elif(centigrados > 35 and centigrados <38):
        print ("Normal")
    else:
        print ("Fiebre")

In [287]:
temperaturas = [33,30,36,37,38,39,40]

list(map(EvaluarTemperatura,temperaturas))




Escalofrios
Escalofrios
Escalofrios
Escalofrios
Escalofrios
Escalofrios
Escalofrios


[None, None, None, None, None, None, None]

In [289]:
texto = "Hola mi nombre es Didier"

In [291]:
# importa el modulo de regular expressions

import re

In [292]:
re.search("mi", texto)

<re.Match object; span=(5, 7), match='mi'>

In [295]:
##MATRICES

import numpy as np


np.random.rand(2,3,4).round(4)

array([[[0.0775, 0.3797, 0.7308, 0.2405],
        [0.5799, 0.5318, 0.1794, 0.5133],
        [0.6867, 0.9966, 0.7499, 0.0127]],

       [[0.2648, 0.0329, 0.4902, 0.5934],
        [0.0316, 0.258 , 0.5993, 0.9238],
        [0.5874, 0.4688, 0.3544, 0.6543]]])

In [297]:
np.random.rand(6)

array([0.93535456, 0.16268361, 0.75874576, 0.41973679, 0.58340008,
       0.38412544])

In [299]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [302]:
arrayEnteros = np.arange(7)
arrayEnteros

array([0, 1, 2, 3, 4, 5, 6])

In [304]:
import random

In [309]:
#funcion para imprimir valores aleatorios mientras la suma de estos no alcance el valor maximo dado
objetivo = 10

x = np.random.randint(0, objetivo, size=(10,))
while sum(x) != objetivo: 
    x = np.random.randint(0, objetivo, size=(10,))

print(x)

[3 2 0 0 1 0 3 0 0 1]


In [314]:
## IMPORTAMOS LA LIBRERIA PANDAS.

import pandas as pda

pda.Series(np.random.randn(5))


0    0.527475
1   -0.776404
2    0.322752
3    0.130025
4   -0.799385
dtype: float64

In [316]:
pda.Series(np.random.randn(5), index = ['a', 'b','c','d','e'])

a    0.295359
b    0.609612
c   -1.103434
d   -0.005660
e   -0.859333
dtype: float64

In [319]:
## Leer un archivo .csv

import sys
sys.path


['D:\\CERTIFIED BIG DATA DEVELOPER\\2020-01-31_Python',
 'C:\\ProgramData\\Anaconda3\\python37.zip',
 'C:\\ProgramData\\Anaconda3\\DLLs',
 'C:\\ProgramData\\Anaconda3\\lib',
 'C:\\ProgramData\\Anaconda3',
 '',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\LENOVO\\.ipython']

In [323]:
data = pda.read_csv('D:\\CERTIFIED BIG DATA DEVELOPER\\2020-01-31_Python/base_intro.csv', sep=',')
data

nit  en_vm_canal1  en_vm_canal2  en_vm_canal3  \
0      C4936394968152386565  0.000000e+00  0.000000e+00  0.000000e+00   
1     C-8615176103348111575  0.000000e+00  0.000000e+00  0.000000e+00   
2      C2364605246729357060  2.509275e+08  5.416089e+07  5.122152e+06   
3      C7393816976826597531  3.940236e+07  9.646900e+07  8.226710e+06   
4       C872645851723947566  3.374323e+08  2.342179e+08  1.053441e+08   
...                     ...           ...           ...           ...   
2228   C-183565186626737291  0.000000e+00  0.000000e+00  0.000000e+00   
2229   C-183565186626737291  0.000000e+00  0.000000e+00  0.000000e+00   
2230   C-183565186626737291  0.000000e+00  0.000000e+00  0.000000e+00   
2231   C-183565186626737291  0.000000e+00  0.000000e+00  0.000000e+00   
2232   C-183565186626737291  0.000000e+00  0.000000e+00  0.000000e+00   

      en_vm_canal4  en_vm_canal5  en_vm_canal6  en_vm_canal7  en_vm_canal8  \
0             0.00           0.0          0.00  0.000000e+00           0.0   
1             0.00           0.0          0.00  0.000000e+00           0.0   
2      41852510.17   413614314.7    1663236.40  2.106848e+09           0.0   
3             0.00           0.0    7072801.90  0.000000e+00     9000000.0   
4      15755286.83           0.0   23671840.33  0.000000e+00     3600962.2   
...            ...           ...           ...           ...           ...   
2228          0.00           0.0          0.00  0.000000e+00           0.0   
2229          0.00           0.0          0.00  0.000000e+00           0.0   
2230          0.00           0.0          0.00  0.000000e+00           0.0   
2231          0.00           0.0          0.00  0.000000e+00           0.0   
2232          0.00           0.0          0.00  0.000000e+00           0.0   

      en_vm_canal9  ...  pagos_pn  tiene_ventas_fisicas  \
0             0.00  ...     0.000                   0.0   
1             0.00  ...     0.000                   0.0   
2             0.00  ...     0.544                   1.0   
3             0.00  ...     0.385                   1.0   
4       3727298.56  ...     0.000                   1.0   
...            ...  ...       ...                   ...   
2228          0.00  ...     0.000                   0.0   
2229          0.00  ...     0.000                   0.0   
2230          0.00  ...     0.000                   0.0   
2231          0.00  ...     0.000                   0.0   
2232          0.00  ...     0.000                   0.0   

     tiene_ventas_electronicas recaudos_pj recaudos_pn rotacion_inventarios  \
0                          0.0         0.0         0.0                  6.0   
1                          0.0         0.0         0.0                  1.0   
2                          0.0         0.0         0.0                  2.0   
3                          0.0         0.0         0.0                  5.0   
4                          0.0         0.0         0.0                  2.0   
...                        ...         ...         ...                  ...   
2228                       0.0         0.0         0.0                  6.0   
2229                       0.0         0.0         0.0                  4.0   
2230                       0.0         0.0         0.0                  2.0   
2231                       0.0         0.0         0.0                  1.0   
2232                       0.0         0.0         0.0                  1.0   

     rotacion_cxc rotacion_cxp ciclo_negocio ciclo_financiero  
0             2.0          2.0           5.0              6.0  
1             3.0          1.0           3.0              4.0  
2             1.0          2.0           2.0              1.0  
3             2.0          3.0           5.0              5.0  
4             2.0          1.0           3.0              3.0  
...           ...          ...           ...              ...  
2228          4.0          4.0           6.0              6.0  
2229          4.0          1.0          

In [329]:
data.head(3)

nit  en_vm_canal1  en_vm_canal2  en_vm_canal3  \
0   C4936394968152386565           0.0          0.00          0.00   
1  C-8615176103348111575           0.0          0.00          0.00   
2   C2364605246729357060   250927492.7   54160892.46    5122151.67   

   en_vm_canal4  en_vm_canal5  en_vm_canal6  en_vm_canal7  en_vm_canal8  \
0          0.00           0.0           0.0  0.000000e+00           0.0   
1          0.00           0.0           0.0  0.000000e+00           0.0   
2   41852510.17   413614314.7     1663236.4  2.106848e+09           0.0   

   en_vm_canal9  ...  pagos_pn  tiene_ventas_fisicas  \
0           0.0  ...     0.000                   0.0   
1           0.0  ...     0.000                   0.0   
2           0.0  ...     0.544                   1.0   

  tiene_ventas_electronicas recaudos_pj recaudos_pn rotacion_inventarios  \
0                       0.0         0.0         0.0                  6.0   
1                       0.0         0.0         0.0                  1.0   
2                       0.0         0.0         0.0                  2.0   

  rotacion_cxc rotacion_cxp ciclo_negocio ciclo_financiero  
0          2.0          2.0           5.0              6.0  
1          3.0          1.0           3.0              4.0  
2          1.0          2.0           2.0              1.0  

[3 rows x 47 columns]

In [331]:
data.tail(3)

nit  en_vm_canal1  en_vm_canal2  en_vm_canal3  \
2230  C-183565186626737291           0.0           0.0           0.0   
2231  C-183565186626737291           0.0           0.0           0.0   
2232  C-183565186626737291           0.0           0.0           0.0   

      en_vm_canal4  en_vm_canal5  en_vm_canal6  en_vm_canal7  en_vm_canal8  \
2230           0.0           0.0           0.0           0.0           0.0   
2231           0.0           0.0           0.0           0.0           0.0   
2232           0.0           0.0           0.0           0.0           0.0   

      en_vm_canal9  ...  pagos_pn  tiene_ventas_fisicas  \
2230           0.0  ...       0.0                   0.0   
2231           0.0  ...       0.0                   0.0   
2232           0.0  ...       0.0                   0.0   

     tiene_ventas_electronicas recaudos_pj recaudos_pn rotacion_inventarios  \
2230                       0.0         0.0         0.0                  2.0   
2231                       0.0         0.0         0.0                  1.0   
2232                       0.0         0.0         0.0                  1.0   

     rotacion_cxc rotacion_cxp ciclo_negocio ciclo_financiero  
2230          2.0          1.0           3.0              4.0  
2231          2.0          1.0           2.0              3.0  
2232          1.0          4.0           2.0              1.0  

[3 rows x 47 columns]

In [333]:
data.shape

(2233, 47)

In [336]:
data[80:500][['pagos_pn','ciclo_negocio']]

pagos_pn  ciclo_negocio
80      0.223            2.0
81      0.458            5.0
82      0.703            4.0
83      0.799            2.0
84      0.535            6.0
..        ...            ...
495     0.426            5.0
496     0.619            2.0
497     0.532            1.0
498     0.703            5.0
499     0.514            5.0

[420 rows x 2 columns]

In [342]:
d = {'c1': pda.Series(['A','B','C']), 'c2': pda.Series([1,2,3,4])}